# Generated by Django 5.2.4 on 2025-07-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_department_alter_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Project Manager'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
