# Generated by Django 5.2.4 on 2025-07-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
