# Generated by Django 5.2.4 on 2025-07-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_department_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
