# Generated by Django 5.1.4 on 2025-04-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
