# Generated by Django 5.2.4 on 2025-07-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_delete_profile'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
