# Generated by Django 5.2.4 on 2025-07-24 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_feedback_project_alter_task_project_and_more'),
        ('project', '0006_alter_comment_project_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_from_data_app', to='project.project'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
