# Generated by Django 5.2.4 on 2025-07-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_comment_project_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
